# Generated by Django 3.2.8 on 2021-10-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=20)),
                ('option2', models.CharField(max_length=20)),
                ('option3', models.CharField(max_length=20)),
                ('question2', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=20)),
                ('option5', models.CharField(max_length=20)),
                ('option6', models.CharField(max_length=20)),
                ('question3', models.CharField(max_length=100)),
                ('option7', models.CharField(max_length=20)),
                ('option8', models.CharField(max_length=20)),
                ('option9', models.CharField(max_length=20)),
                ('question4', models.CharField(max_length=100)),
                ('option10', models.CharField(max_length=20)),
                ('option11', models.CharField(max_length=20)),
                ('option12', models.CharField(max_length=20)),
                ('question5', models.CharField(max_length=100)),
                ('option13', models.CharField(max_length=20)),
                ('option14', models.CharField(max_length=20)),
                ('option15', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
